import { tagsNS } from '../isomorphic/index.js'
let _tagsNS, svg_tags
export function svg_tags_() {
	if (_tagsNS !== tagsNS) {
		_tagsNS = tagsNS
		svg_tags = _tagsNS?.('http://www.w3.org/2000/svg')
	}
	return svg_tags
}
export let a_ = (...arg_a)=>svg_tags_().a(...arg_a)
export let animate_ = (...arg_a)=>svg_tags_().animate(...arg_a)
export let animateMotion_ = (...arg_a)=>svg_tags_().animateMotion(...arg_a)
export let animateTransform_ = (...arg_a)=>svg_tags_().animateTransform(...arg_a)
export let circle_ = (...arg_a)=>svg_tags_().circle(...arg_a)
export let clipPath_ = (...arg_a)=>svg_tags_().clipPath(...arg_a)
export let defs_ = (...arg_a)=>svg_tags_().defs(...arg_a)
export let desc_ = (...arg_a)=>svg_tags_().desc(...arg_a)
export let ellipse_ = (...arg_a)=>svg_tags_().ellipse(...arg_a)
export let feBlend_ = (...arg_a)=>svg_tags_().feBlend(...arg_a)
export let feColorMatrix_ = (...arg_a)=>svg_tags_().feColorMatrix(...arg_a)
export let feComponentTransfer_ = (...arg_a)=>svg_tags_().feComponentTransfer(...arg_a)
export let feComposite_ = (...arg_a)=>svg_tags_().feComposite(...arg_a)
export let feConvolveMatrix_ = (...arg_a)=>svg_tags_().feConvolveMatrix(...arg_a)
export let feDiffuseLighting_ = (...arg_a)=>svg_tags_().feDiffuseLighting(...arg_a)
export let feDisplacementMap_ = (...arg_a)=>svg_tags_().feDisplacementMap(...arg_a)
export let feDistantLight_ = (...arg_a)=>svg_tags_().feDistantLight(...arg_a)
export let feDropShadow_ = (...arg_a)=>svg_tags_().feDropShadow(...arg_a)
export let feFlood_ = (...arg_a)=>svg_tags_().feFlood(...arg_a)
export let feFuncA_ = (...arg_a)=>svg_tags_().feFuncA(...arg_a)
export let feFuncB_ = (...arg_a)=>svg_tags_().feFuncB(...arg_a)
export let feFuncG_ = (...arg_a)=>svg_tags_().feFuncG(...arg_a)
export let feFuncR_ = (...arg_a)=>svg_tags_().feFuncR(...arg_a)
export let feGaussianBlur_ = (...arg_a)=>svg_tags_().feGaussianBlur(...arg_a)
export let feImage_ = (...arg_a)=>svg_tags_().feImage(...arg_a)
export let feMerge_ = (...arg_a)=>svg_tags_().feMerge(...arg_a)
export let feMergeNode_ = (...arg_a)=>svg_tags_().feMergeNode(...arg_a)
export let feMorphology_ = (...arg_a)=>svg_tags_().feMorphology(...arg_a)
export let feOffset_ = (...arg_a)=>svg_tags_().feOffset(...arg_a)
export let fePointLight_ = (...arg_a)=>svg_tags_().fePointLight(...arg_a)
export let feSpecularLighting_ = (...arg_a)=>svg_tags_().feSpecularLighting(...arg_a)
export let feSpotLight_ = (...arg_a)=>svg_tags_().feSpotLight(...arg_a)
export let feTile_ = (...arg_a)=>svg_tags_().feTile(...arg_a)
export let feTurbulence_ = (...arg_a)=>svg_tags_().feTurbulence(...arg_a)
export let filter_ = (...arg_a)=>svg_tags_().filter(...arg_a)
export let foreignObject_ = (...arg_a)=>svg_tags_().foreignObject(...arg_a)
export let g_ = (...arg_a)=>svg_tags_().g(...arg_a)
export let image_ = (...arg_a)=>svg_tags_().image(...arg_a)
export let line_ = (...arg_a)=>svg_tags_().line(...arg_a)
export let linearGradient_ = (...arg_a)=>svg_tags_().linearGradient(...arg_a)
export let marker_ = (...arg_a)=>svg_tags_().marker(...arg_a)
export let mask_ = (...arg_a)=>svg_tags_().mask(...arg_a)
export let metadata_ = (...arg_a)=>svg_tags_().metadata(...arg_a)
export let mpath_ = (...arg_a)=>svg_tags_().mpath(...arg_a)
export let path_ = (...arg_a)=>svg_tags_().path(...arg_a)
export let pattern_ = (...arg_a)=>svg_tags_().pattern(...arg_a)
export let polygon_ = (...arg_a)=>svg_tags_().polygon(...arg_a)
export let polyline_ = (...arg_a)=>svg_tags_().polyline(...arg_a)
export let radialGradient_ = (...arg_a)=>svg_tags_().radialGradient(...arg_a)
export let rect_ = (...arg_a)=>svg_tags_().rect(...arg_a)
export let script_ = (...arg_a)=>svg_tags_().script(...arg_a)
export let set_ = (...arg_a)=>svg_tags_().set(...arg_a)
export let stop_ = (...arg_a)=>svg_tags_().stop(...arg_a)
export let style_ = (...arg_a)=>svg_tags_().style(...arg_a)
export let svg_ = (...arg_a)=>svg_tags_().svg(...arg_a)
export let switch_ = (...arg_a)=>svg_tags_().switch(...arg_a)
export let symbol_ = (...arg_a)=>svg_tags_().symbol(...arg_a)
export let text_ = (...arg_a)=>svg_tags_().text(...arg_a)
export let textPath_ = (...arg_a)=>svg_tags_().textPath(...arg_a)
export let title_ = (...arg_a)=>svg_tags_().title(...arg_a)
export let tspan_ = (...arg_a)=>svg_tags_().tspan(...arg_a)
export let use_ = (...arg_a)=>svg_tags_().use(...arg_a)
export let view_ = (...arg_a)=>svg_tags_().view(...arg_a)
